version: "3.3"

services:
  redis-server:
    image: redis
    ports:
      - "6379:6379"
      
  angular:
    build: angular-client
    ports:
      - "4200:4200"
    environment:
      SERVER_HOST: http://localhost:3000
      SERVER_PORT: 3000
      REDIS_NOTIF_CHANNEL: app:notifications
    labels:
      kompose.service.type: LoadBalancer

  express:
    depends_on:
      - redis-server
    build: express-server
    environment:
      SERVER_HOST: http://localhost:3000
      SERVER_PORT: 3000
      REDIS_NOTIF_CHANNEL: app:notifications
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    links: [ redis-server ]

  tf-triplet-model:
    build: dlClassifier
    volumes:
      - /home/esen-baha/esen_iot/iot-app/test:/app/test
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      SEGLEN: 1024
    links: [ redis-server ]
