#!/bin/bash

RECORD_FILE_DIR_LOCAL = "" #Record File Directory in Local PC
BURST_FILE_DIR_LOCAL = "" #Burst File Directory in Local PC

RECORD_FILE_DIR = "/app/data/tuncer_unknown_unprocessed" #DO NOT CHANGE
BURST_FILE_DIR = "/app/data/new_dataset" #DO NOT CHANGE
F_SAMPLING = 55000000
WIFI_BW = 20000000
PROPS_SDR = "Sdr\ pozisyon\ ID"
PROPS_P_FIRST ="P00"
PROPS_DEVICE = "Cihaz\ Pozisyon\ ID"
PROPS_P_SECOND = "P01"
PROPS_SDR_ID = "Sdr\ ID"
PROPS_SDR_SECOND = "SDR-02"
ACCESS_POINT_MAC = "74EA3AE6BF7D"
MAC_ADDRESSES_IN_BLACK_LIST = "a"
MIN_SNR = 5
IS_LIVE = "true"


docker run --rm -e "DISPLAY=: 1" -v /tmp/.X11-unix:/tmp/.X11-unix -v $RECORD_FILE_DIR_LOCAL:/app/data/tuncer_unknown_unprocessed -v $BURST_FILE_DIR_LOCAL:/app/data/new_dataset -e RECORD_FILE_DIR=$RECORD_FILE_DIR -e BURST_FILE_DIR=$BURST_FILE_DIR -e F_SAMPLING=$F_SAMPLING -e WIFI_BW=$WIFI_BW -e PROPS_SDR=$PROPS_SDR -e PROPS_P_FIRST=$PROPS_P_FIRST -e PROPS_DEVICE=$PROPS_DEVICE -e PROPS_P_SECOND=$PROPS_P_SECOND -e PROPS_SDR_ID=$PROPS_SDR_ID -e PROPS_SDR_SECOND=$PROPS_SDR_SECOND -e ACCESS_POINT_MAC=$ACCESS_POINT_MAC -e MAC_ADDRESSES_IN_BLACK_LIST=$MAC_ADDRESSES_IN_BLACK_LIST -e MIN_SNR=$MIN_SNR -e IS_LIVE=$IS_LIVE signal-acquire